import type { Metadata } from 'next'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import Header from '../partials/Header'
import { archivo, openSans } from '../helpers/fonts'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <ClerkProvider>
                <body className={`${archivo.variable} ${openSans.variable} bg-gray-900`}> 
                    <Header />     
                    {children}
                </body>
            </ClerkProvider>
        </html>
    )
}
